version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - NEXT_PUBLIC_RECAPTCHA_ENABLED=false
      - REDIS_CACHE_ENABLED=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./messages:/app/messages
      - ./.env:/app/.env
      - .:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: 